Repository SOPT-all/36-STUDY-WEB-REACT-DOCS, pull requests merged in 2025-05, with the labels that each got.

#3 [Week1] 예지 - UI 표현하기 (컴포넌트, JSX, props)
  docs/Yeji/Week1/README.md
  docs/Yeji/Week1/images/import-export.svg
Labels: 1주차, 예지

#2 [Week2] 시연 - UI 표현하기 (조건부 렌더링, 리스트 렌더링, 순수성)
  practice/Siyeon/week2/components/PersonCard.jsx
  practice/Siyeon/week2/components/PersonDetail.jsx
  practice/Siyeon/week2/src/App.css
  practice/Siyeon/week2/src/App.jsx
  practice/Siyeon/week2/src/data.js
  practice/Siyeon/week2/yarn.lock
Labels: 2주차, 시연

#9 [Week3] 시연 - 상호작용 더하기(이벤트 응답, State, 렌더링, 스냅샷)
  docs/Siyeon/week3/README.md
  docs/Siyeon/week3/image-1.png
  docs/Siyeon/week3/image-2.png
  docs/Siyeon/week3/image-3.png
  docs/Siyeon/week3/image.png
Labels: 시연, 3주차

#4 [Week2] 예지 - UI 표현하기 (조건부 렌더링, 리스트 렌더링, 순수성)
  docs/Yeji/Week2/README.md
  practice/Yeji/Week2/week2-practice/.gitignore
  practice/Yeji/Week2/week2-practice/README.md
  practice/Yeji/Week2/week2-practice/eslint.config.js
  practice/Yeji/Week2/week2-practice/index.html
  practice/Yeji/Week2/week2-practice/package.json
  practice/Yeji/Week2/week2-practice/public/vite.svg
  practice/Yeji/Week2/week2-practice/src/App.jsx
  practice/Yeji/Week2/week2-practice/src/assets/react.svg
  practice/Yeji/Week2/week2-practice/src/components/PersonCard.jsx
  practice/Yeji/Week2/week2-practice/src/components/PersonDetail.jsx
  practice/Yeji/Week2/week2-practice/src/data.js
  practice/Yeji/Week2/week2-practice/src/index.css
  practice/Yeji/Week2/week2-practice/src/main.jsx
  practice/Yeji/Week2/week2-practice/vite.config.js
  practice/Yeji/Week2/week2-practice/yarn.lock
Labels: 2주차, 예지

#5 [Week2] 소이 - UI 표현하기 (조건부 렌더링, 리스트 렌더링, 순수성)
  docs/Soy/week2/images/1.webp
  docs/Soy/week2/images/2.png
  docs/Soy/week2/week2.md
  practice/Soy/week2/.gitignore
  practice/Soy/week2/README.md
  practice/Soy/week2/package-lock.json
  practice/Soy/week2/package.json
  practice/Soy/week2/public/index.html
  practice/Soy/week2/src/App.css
  practice/Soy/week2/src/App.js
  practice/Soy/week2/src/components/PersonCard.js
  practice/Soy/week2/src/components/PersonCardStyle.css
  practice/Soy/week2/src/components/PersonDetail.js
  practice/Soy/week2/src/components/PersonDetailStyle.css
  practice/Soy/week2/src/data.js
  practice/Soy/week2/src/index.css
  practice/Soy/week2/src/index.js
Labels: 2주차, 소이

#6 [Week3] 소이 - 상호작용 더하기(이벤트 응답, State, 렌더링, 스냅샷)
  docs/Soy/week3/README.md
  docs/Soy/week3/images/image.png
  docs/Soy/week3/images/image2.png
Labels: 소이, 3주차

#7 [Week3] 예지 - 상호작용 더하기(이벤트 응답, State, 렌더링, 스냅샷)
  docs/Yeji/Week3/README.md
Labels: 예지, 3주차

#8 [Week3] 예원 - 상호작용 더하기(이벤트 응답, State, 렌더링, 스냅샷)
  docs/Yewon/Week2/README.md
  docs/Yewon/Week3/README.md
Labels: 예원, 3주차

#10 [Week4] 예원 - 상호작용 더하기(state, 객체, 배열 업데이트)
  docs/Yewon/Week4/Readme.md
Labels: 예원, 4주차
