Repository SOPT-all/36-STUDY-WEB-REACT-DOCS, pull requests merged in 2025-06, with the labels that each got.

#17 [Week5]: 시연 - State 관리하기
  docs/Siyeon/week5/README.md
  docs/Siyeon/week5/image-1.png
  docs/Siyeon/week5/image-2.png
  docs/Siyeon/week5/image-3.png
  docs/Siyeon/week5/image.png
Labels: 시연, 5주차

#14 [Week6] 예지 - 탈출구 (ref, effect)
  docs/Yeji/Week6/README.md
Labels: 예지, 6주차

#16 [Week6]: 예원 - 탈출구 (ref, effect)
  docs/Yewon/Week4/Readme.md
  docs/Yewon/Week5/README.md
  docs/Yewon/Week6/README.md
Labels: 예원, 6주차

#18 [Week6]: 소이 - 탈출구 (ref, effect)
  docs/Soy/week6/week6.md
Labels: 소이, 6주차
